// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodBookingSystem.C.RepositoryLayer.Models;

public partial class BookingDetail
{
    public int BookingDetailId { get; set; }

    public int RoomId { get; set; }

    public int BookingId { get; set; }

    public string BookingType { get; set; }

    public decimal TotalPrice { get; set; }

    public DateTime? Timestamp { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Room Room { get; set; }
}