// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodBookingSystem.C.RepositoryLayer.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int UserId { get; set; }

    public DateOnly BookingDate { get; set; }

    public decimal Total { get; set; }

    public string Status { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual Feedback Feedback { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual ICollection<RoomSlot> RoomSlots { get; set; } = new List<RoomSlot>();

    public virtual Account User { get; set; }
}