// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodBookingSystem.C.RepositoryLayer.Models;

public partial class Feedback
{
    public int FeedbackId { get; set; }

    public int BookingId { get; set; }

    public string Description { get; set; }

    public int? Rating { get; set; }

    public DateTime? Timestamp { get; set; }

    public virtual Booking Booking { get; set; }
}