// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodBookingSystem.C.RepositoryLayer.Models;

public partial class Room
{
    public int RoomId { get; set; }

    public string Name { get; set; }

    public int Capacity { get; set; }

    public string Status { get; set; }

    public decimal? Price { get; set; }

    public decimal? PriceDay { get; set; }

    public int TypeId { get; set; }

    public string Description { get; set; }

    public string ImgUrl { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual ICollection<RoomSlot> RoomSlots { get; set; } = new List<RoomSlot>();

    public virtual RoomType Type { get; set; }
}