// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodBookingSystem.C.RepositoryLayer.Models;

public partial class RoomSlot
{
    public int SlotId { get; set; }

    public int RoomId { get; set; }

    public int? BookingId { get; set; }

    public DateOnly? BookingDate { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Room Room { get; set; }

    public virtual Slot Slot { get; set; }
}