// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PodBookingSystem.C.RepositoryLayer.Models;

public partial class Slot
{
    public int SlotId { get; set; }

    public string Description { get; set; }

    public virtual ICollection<RoomSlot> RoomSlots { get; set; } = new List<RoomSlot>();
}