// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PodBookingSystem.C.RepositoryLayer.Models;
using System;
using System.Collections.Generic;

namespace PodBookingSystem.C.RepositoryLayer.DBConext;

public partial class PodBookingSystemContext : DbContext
{
    public PodBookingSystemContext()
    {
    }

    public PodBookingSystemContext(DbContextOptions<PodBookingSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingDetail> BookingDetails { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<RoomSlot> RoomSlots { get; set; }

    public virtual DbSet<RoomType> RoomTypes { get; set; }

    public virtual DbSet<Slot> Slots { get; set; }

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=HakaryiPC\\SQL2306;Initial Catalog=PodBookingSystem;User ID=sa;Password=12345;Encrypt=False");

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.AccId).HasName("PK__Account__9A20D55406593CB4");

            entity.ToTable("Account");

            entity.HasIndex(e => e.Email, "UQ__Account__AB6E61646C50EA94").IsUnique();

            entity.HasIndex(e => e.Username, "UQ__Account__F3DBC572A2D572D8").IsUnique();

            entity.Property(e => e.AccId).HasColumnName("acc_id");
            entity.Property(e => e.AvatarUrl)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("avatarUrl");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.RoleId).HasColumnName("role_ID");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("username");
            entity.Property(e => e.Vip)
                .HasDefaultValue(false)
                .HasColumnName("VIP");

            entity.HasOne(d => d.Role).WithMany(p => p.Accounts)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Account__role_ID__3C69FB99");
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Booking__5DE2B9A9FDB6F85A");

            entity.ToTable("Booking");

            entity.Property(e => e.BookingId).HasColumnName("booking_ID");
            entity.Property(e => e.BookingDate).HasColumnName("Booking_date");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("Pending")
                .HasColumnName("status");
            entity.Property(e => e.Total).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.UserId).HasColumnName("user_ID");

            entity.HasOne(d => d.User).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Booking__user_ID__47DBAE45");
        });

        modelBuilder.Entity<BookingDetail>(entity =>
        {
            entity.HasKey(e => e.BookingDetailId).HasName("PK__Booking___647F4A7B0655A54C");

            entity.ToTable("Booking_Detail");

            entity.Property(e => e.BookingDetailId).HasColumnName("booking_detail_ID");
            entity.Property(e => e.BookingId).HasColumnName("booking_ID");
            entity.Property(e => e.BookingType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Booking_Type");
            entity.Property(e => e.EndTime).HasColumnName("End_time");
            entity.Property(e => e.RoomId).HasColumnName("room_ID");
            entity.Property(e => e.StartTime).HasColumnName("Start_time");
            entity.Property(e => e.Timestamp)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("timestamp");
            entity.Property(e => e.TotalPrice)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("total_price");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingDetails)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Booking_D__booki__5165187F");

            entity.HasOne(d => d.Room).WithMany(p => p.BookingDetails)
                .HasForeignKey(d => d.RoomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Booking_D__room___5070F446");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackId).HasName("PK__Feedback__CD3992F81E04FF33");

            entity.ToTable("Feedback");

            entity.HasIndex(e => e.BookingId, "UQ__Feedback__5DE2B9A832E66DA9").IsUnique();

            entity.Property(e => e.FeedbackId).HasColumnName("Feedback_ID");
            entity.Property(e => e.BookingId).HasColumnName("booking_ID");
            entity.Property(e => e.Description).IsUnicode(false);
            entity.Property(e => e.Timestamp)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("timestamp");

            entity.HasOne(d => d.Booking).WithOne(p => p.Feedback)
                .HasForeignKey<Feedback>(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Feedback__bookin__5AEE82B9");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payment__DA6C7FE14571AED1");

            entity.ToTable("Payment");

            entity.HasIndex(e => e.BookingId, "UQ__Payment__5DE2B9A8DD87FB42").IsUnique();

            entity.Property(e => e.PaymentId).HasColumnName("Payment_ID");
            entity.Property(e => e.BookingId).HasColumnName("booking_ID");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Total_amount");

            entity.HasOne(d => d.Booking).WithOne(p => p.Payment)
                .HasForeignKey<Payment>(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__booking__5535A963");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Role__3213E83F5E258E59");

            entity.ToTable("Role");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Role_name");
        });

        modelBuilder.Entity<Room>(entity =>
        {
            entity.HasKey(e => e.RoomId).HasName("PK__Room__19645EB26AA3BB10");

            entity.ToTable("Room");

            entity.Property(e => e.RoomId).HasColumnName("room_ID");
            entity.Property(e => e.Capacity).HasColumnName("capacity");
            entity.Property(e => e.Description).IsUnicode(false);
            entity.Property(e => e.ImgUrl)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("img_url");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.PriceDay)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Price/Day");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("Available")
                .HasColumnName("status");
            entity.Property(e => e.TypeId).HasColumnName("Type_id");

            entity.HasOne(d => d.Type).WithMany(p => p.Rooms)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Room__Type_id__4222D4EF");
        });

        modelBuilder.Entity<RoomSlot>(entity =>
        {
            entity.HasKey(e => new { e.SlotId, e.RoomId }).HasName("PK__Room_Slo__3B7B4847D45027FD");

            entity.ToTable("Room_Slot");

            entity.Property(e => e.SlotId).HasColumnName("Slot_id");
            entity.Property(e => e.RoomId).HasColumnName("Room_Id");
            entity.Property(e => e.BookingDate).HasColumnName("Booking_Date");
            entity.Property(e => e.BookingId).HasColumnName("Booking_id");

            entity.HasOne(d => d.Booking).WithMany(p => p.RoomSlots)
                .HasForeignKey(d => d.BookingId)
                .HasConstraintName("FK__Room_Slot__Booki__4CA06362");

            entity.HasOne(d => d.Room).WithMany(p => p.RoomSlots)
                .HasForeignKey(d => d.RoomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Room_Slot__Room___4BAC3F29");

            entity.HasOne(d => d.Slot).WithMany(p => p.RoomSlots)
                .HasForeignKey(d => d.SlotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Room_Slot__Slot___4AB81AF0");
        });

        modelBuilder.Entity<RoomType>(entity =>
        {
            entity.HasKey(e => e.TypeId).HasName("PK__Room_Typ__FE91E1E6802CAFA0");

            entity.ToTable("Room_Type");

            entity.Property(e => e.TypeId).HasColumnName("Type_id");
            entity.Property(e => e.Description).IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Slot>(entity =>
        {
            entity.HasKey(e => e.SlotId).HasName("PK__Slot__1AE5AEE658F18B18");

            entity.ToTable("Slot");

            entity.Property(e => e.SlotId).HasColumnName("Slot_id");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("description");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}